language:
    - cpp
    
compiler:
    - clang

before_install:
    # libstdc++-4.8-dev
    - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
    # clang++-3.2
    - sudo add-apt-repository --yes ppa:h-rayflood/llvm
    - sudo apt-get -qq update

install:
    - sudo apt-get -qq install libstdc++-4.8-dev clang-3.2

script:
    - clang++ -stdlib=libstdc++ -std=c++11 test.cpp -o prog && ./prog
