language:
    - cpp
    
compiler:
    - clang

before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update

install:
    - sudo apt-get install libstdc++-4.8-dev

script:
    - clang++ -std=c++11 test.cpp -o prog && ./prog
