sudo:
  - false

language:
  - cpp

compiler:
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.8-dev

script:
  - which clang++
  - clang++ --version
  - clang++ -std=c++11 test.cpp -o prog && ./prog
